apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- marketplace.yaml
  - mart.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: hcp-mart-schema-
    patch: |-
      - op: move
        from: /metadata/name
        path: /metadata/generateName   
