apiVersion: batch/v1
kind: Job
metadata:
  name: hcp-mart-schema-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app.kubernetes.io/instance: hcp-mart-schema
    app.kubernetes.io/name: hcp-mart-schema
spec:
  #ttlSecondsAfterFinished: 130
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hcp-mart-schema
        app.kubernetes.io/name: hcp-mart-schema
        #job-name: hcp-mart-schema
    spec:
      containers:
      - name: hcp-mart-schema
        image: alpsd
        imagePullPolicy: IfNotPresent
      restartPolicy: Never   
